name: Atualiza versão do README.md após novo release

on:
  release:
    types: [published]
  workflow_dispatch: # Permite execução manual do workflow

permissions:
  contents: write

jobs:
  update-readme-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Garante que todo o histórico seja baixado
          ref: main       # Troque para sua branch padrão se não for "main"

      - name: Garante que está na branch principal
        run: git checkout main  # Troque "main" para sua branch padrão se necessário

      - name: Define a versão manualmente caso em execução manual
        run: |
          if [ -z "${{ github.event.release.tag_name }}" ]; then
            # Se rodar manualmente, defina a versão como input ou padrão
            VERSION="${{ inputs.versao || '0.0.0.0' }}"
          else
            VERSION="${{ github.event.release.tag_name }}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Atualiza README.md com a nova versão
        run: |
          README="README.md"
          VERSION="${{ env.VERSION }}"
          # Atualiza todas as ocorrências multilíngues da versão no README.md
          sed -i -E "s/(Versão: )[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/\1$VERSION/g" $README
          sed -i -E "s/(Version: )[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/\1$VERSION/g" $README
          sed -i -E "s/(Versión: )[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/\1$VERSION/g" $README
          sed -i -E "s/(Version : )[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/\1$VERSION/g" $README
          sed -i -E "s/(Versione: )[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/\1$VERSION/g" $README
          sed -i -E "s/(Version: )[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/\1$VERSION/g" $README

      - name: Commit e push da atualização automática
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualização automática da versão do README.md para ${{ env.VERSION }}"
          add: README.md
          default_author: github_actions
          push: true
          branch: main  # Troque para sua branch padrão se necessário
